name: Create release to make .exe published.

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    # CREATE RELEASE AND UPLOAD EXECUTABLE FILE
    create-releases:
        runs-on: windows-latest
        needs: [build-on-windows, build-on-ubuntu]
        steps:
            # CHECKOUT REPOSITORY
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
            # DOWNLOAD CRATE
          - name: crate をダウンロード
            run: |
                Invoke-WebRequest -Uri "https://github.com/mass10/r-gh-create-release/releases/latest/download/r-gh-create-release.exe" -OutFile "r-gh-create-release.exe"
            # DOWNLOAD ARTIFACTS
          - name: Download artifacts
            uses: actions/download-artifact@v2
            with:
                name: my-temporary-artifacts
            # CREATE RELEASE AND UPLOAD EXECUTABLE FILE
          - name: release を作成して実行ファイルを公開
            run: |
                .\r-gh-create-release `
                    --file target/gh-release-storategy-example-1.exe `
                    --file target/gh-release-storategy-example-1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                

    # FOR WINDOWS
    build-on-windows:
        runs-on: windows-latest
        steps:
            # CHECKOUT REPOSITORY
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
            # BUILD APPLICATION FOR WINDOWS
          - name: Create the app package
            run: cargo.exe build --release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # CREATE ARTIFACTS
          - name: Create Release
            uses: actions/upload-artifact@v3
            with:
                name: my-temporary-artifacts
                path: target/gh-release-storategy-example-1.exe

    # FOR LINUX
    build-on-linux:
        runs-on: ubuntu-latest
        steps:
            # CHECKOUT REPOSITORY
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 1
            # BUILD APPLICATION FOR WINDOWS
          - name: Create the app package
            run: cargo build --release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # CREATE ARTIFACTS
          - name: Create Release
            uses: actions/upload-artifact@v3
            with:
                name: my-temporary-artifacts
                path: target/gh-release-storategy-example-1
